urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^prkl/', include('prkl.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^', include('web.urls')),
)

web/forms.py
# vim: tabstop=4 expandtab autoindent shiftwidth=4 fileencoding=utf-8

from django.contrib.auth import authenticate
from django.contrib.auth import models as auth_models
from django.contrib.auth import tokens

from django.db.transaction import commit_on_success

from django.utils.html import conditional_escape, force_unicode

from django.utils.safestring import mark_safe

from django import forms

from web import models
from web import utils

import datetime

## Widget land
from django.forms.util import flatatt
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape

class PrklTextarea(forms.widgets.Textarea):
    def render(self, name, value, attrs=None):
        if value is None:
            value = ''
        value = force_unicode(value)
        final_attrs = self.build_attrs(attrs, name=name)
        return mark_safe(u'<br /><textarea%s>%s</textarea>' % (flatatt(final_attrs), conditional_escape(force_unicode(value))))

## SuperClass Me (harder)

class PrklErrorField(forms.util.ErrorList):
    def __unicode__(self):
        return self.as_prkl()

    def as_prkl(self):
        if not self:
            return ''

        return mark_safe('%s'
            % ''.join([u'%s<br />' % conditional_escape(force_unicode(e)) for e in self]))


class PrklSuperForm(forms.Form):
    def __init__(self, *args, **kwargs):
        kwargs['error_class'] = PrklErrorField
        forms.Form.__init__(self, *args, **kwargs)

    def as_prkl(self):
        # normal_row, error_row, row_ender, help_text_html, errors_on_separate_row
        normal_row = """
<p>
    <div>
    <b>%(label)s</b>
    %(field)s
</div>
    <span class="error">%(errors)s</span>
    %(help_text)s
"""
        error_row = '<span style="color: red;">%s</span>'
        row_ender = '</p>'
        help_text_html = ' %s'
        errors_on_separate_row = False

        return self._html_output(normal_row, error_row, row_ender, help_text_html, errors_on_separate_row)

    def as_prkl_all_req(self):
        # normal_row, error_row, row_ender, help_text_html, errors_on_separate_row
        normal_row = '<p><div><span class="required">*</span>%(label)s</div> <br />%(field)s <br /><span class="error">%(errors)s</span> %(help_text)s '
        error_row = '<span style="color: red;">%s</span>'
        row_ender = '</p>'
        help_text_html = ' %s'
        errors_on_separate_row = False

        return self._html_output(normal_row, error_row, row_ender, help_text_html, errors_on_separate_row)

## Children

class RequestResetForm(PrklSuperForm):
    error_messages = {
        'required': 'Tämä kenttä tarvitaan',
        'invalid': 'Epävalidi sähköpostiosoite',
    }

    email = forms.EmailField(label='Sähköpostisi', error_messages=error_messages)

    def clean_email(self):
        try:
            user = models.User.objects.get(email=self.data['email'])
            self.data['user'] = user
        except models.User.DoesNotExist:
            raise forms.ValidationError('Sähköpostiosoitetta ei löytynyt')

        return self.data['email']

    @commit_on_success
    def save(self):
        # Generate token
        token_generator = tokens.PasswordResetTokenGenerator()

        # Smuggle user again
        user = self.data['user']

        token = token_generator.make_token(user)
        reset_request, created = models.ResetRequest.objects.get_or_create(
            user = user,
            token = token
        )

        return token


class PasswordResetForm(PrklSuperForm):
    error_messages = {
        'required': 'Annathan uuden salasanasi :)'
    }
    new_password = forms.CharField(label='Uusi salasana', error_messages=error_messages, widget=forms.widgets.PasswordInput())


class LoginForm(PrklSuperForm):
    # Localizbation
    error_messages = {
        'required': 'Tämä kenttä tarvitaan',
    }

    # Widget attributes
    attrs = {
        'size': 12,
    }

    username = forms.CharField(label='Tunnus', error_messages=error_messages, widget=forms.widgets.TextInput(attrs=attrs))
    password = forms.CharField(label='Salasana', error_messages=error_messages, widget=forms.widgets.PasswordInput(attrs=attrs))

    def clean_username(self):
        username = self.data.get('username', '').strip()
        password = self.data.get('password', '')

        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError('Nimi tai salasana väärä')

        return self.data['username']


class RegisterForm(PrklSuperForm):
    # Custom Finnish error messages
    error_messages = {
        'required': 'Tämä kenttä tarvitaan',
        'invalid': 'Epävalidi sähköpostiosoite',
    }

    # Widget attributes
    attrs = {
        'size': 12,
    }

    reg_username = forms.CharField(label='Tunnus', error_messages=error_messages, widget=forms.widgets.TextInput(attrs=attrs))
    reg_password = forms.CharField(label='Salasana', error_messages=error_messages, widget=forms.widgets.PasswordInput(attrs=attrs))
    reg_email = forms.EmailField(label='Sähköposti', error_messages=error_messages, widget=forms.widgets.TextInput(attrs=attrs))

    def clean_reg_username(self):
        username = self.data.get('reg_username', '').strip()

        if not username:
            raise forms.ValidationError('Tunnus tarvitaan')

        exists = (auth_models.User.objects.filter(username__iexact=username).count() > 0)
        if exists:
            raise forms.ValidationError('Tunnus on jo otettu')

        return username

    def clean_reg_email(self):
        email = self.data.get('reg_email', '').strip()
        if not email:
            raise forms.ValidationError('Sähköposti tarvitaan')

        exists = (auth_models.User.objects.filter(email=email).count() > 0)
        if exists:
            raise forms.ValidationError('Sähköposti on jo otettu')

        return email

    @commit_on_success
    def save(self):
        # Create new user
        username = self.cleaned_data['reg_username']
        password = self.cleaned_data['reg_password']
        email = self.cleaned_data['reg_email']
        user = models.User()
        user.username = username
        user.email = email
        # Until the confirmation is in
        user.is_active = False
        user.set_password(password)

        user.save()

        ## Give vip even if registered user doesn't confirm so the inviter doesn't feel screwed
        # Also see if this was an invite
        try:
            invite = models.FriendInvite.objects.get(recipient=email)
            invite.registered_at = datetime.datetime.now()
            user_invite_count = models.FriendInvite.objects.filter(sent_by_user=invite.sent_by_user, registered_at__isnull=False).count()
            if user_invite_count < 6:
                if invite.sent_by_user.is_vip:
                    invite.sent_by_user.extend_vip(datetime.timedelta(days=5))
                else:
                    invite.sent_by_user.set_vip(datetime.datetime.now() + datetime.timedelta(days=5))
            invite.save()
        except models.FriendInvite.DoesNotExist:
            pass
        return user


class SubmitPrklForm(PrklSuperForm):
    content_error_messages = {
        'required': 'Taisi jäädä prkl kirjoittamatta!',
    }
    tag_error_messages = {
        'invalid_choice': 'Tänään vaihtoehto %(value)s ei ole listassa prkl',
        'invalid_list': 'Lista ei ole pätevä',
        'required': 'Jotain tarvitaan, valitse edes Satunnainen ;)',
    }
    attrs = {
        'cols': 55,
        'rows': 3,
    }
    content = forms.CharField(label='Sinun prkleesi', error_messages=content_error_messages, widget=PrklTextarea(attrs=attrs))
    tags = forms.MultipleChoiceField(label='Tagit', error_messages=tag_error_messages, choices=(), widget=forms.widgets.CheckboxSelectMultiple())

    def clean_content(self):
        content = self.data['content'].strip()

        if not content.lower().startswith('tänään'):
            raise forms.ValidationError('Aloitathan Prkleesi sanalla tänään')

        if not content.lower().endswith('prkl'):
            if content[-1] == '.' or content[-1] == '!':
                if not content[-5:-1].lower() == 'prkl':
                    raise forms.ValidationError('Päätäthän Prkleesi sanalla prkl')
            else:
                raise forms.ValidationError('Päätäthän Prkleesi sanalla prkl')

        if len(content) > 1024:
            raise forms.ValidationError('Tänään prkleesi on yli 1024 merkkiä prkl')

        return '%s%s' % ('T', content[1:])

    @commit_on_success
    def save(self):
        new_prkl = models.Prkl()
        new_prkl.content = self.cleaned_data['content']
        user = self.data['user']
        if user.id:
            # See if someone set an anonymity here
            if not self.data.has_key('anonymous'):
                new_prkl.user = user
        new_prkl.save()
        new_prkl.tag.add(*self.cleaned_data['tags'])

        # TWEET
        from qs.queue import models as queue_models
        # Maybe F() objects would help but we don't have them
        twit_queue = queue_models.Queue.objects.get(name= 'twitter')

        tweet = utils.make_tweet(new_prkl)
        tweet_message = queue_models.Message.objects.create(message=tweet, queue=twit_queue)

        new_prkl.queue_message.add(tweet_message)
        new_prkl.save()

        return new_prkl

class CommentPrklForm(PrklSuperForm):
    error_messages = {
        'required': 'Kirjoitathan kommentin!',
    }

    attrs = {
        'rows': 5,
        'cols': 55,
    }

    content = forms.CharField(label='Kommentti', error_messages=error_messages, widget=PrklTextarea(attrs=attrs))

    def clean_content(self):
        return self.data.get('content', '').strip()

    @commit_on_success
    def save(self):
        prkl_comment = models.PrklComment()

        prkl_comment.prkl_id = self.data['prkl_id']
        if self.data['user'].id:
            prkl_comment.commenting_user = self.data['user']

web/templates/about_vip.html
{% extends "base.html" %}

{% block content %}
<div class="about_vip">
	<h1>Tänään kerron VIPistä, prkl</h1>
	<p>
	VIPiksi liittyminen kannattaa, saat käytettäviisi mm. prkleidesi suosion mittaamisen
	sekä laajemman käyttäjähaun.
	</p>
	<p>
	Profiiliisi saat kuvan ja kuvauksen!
	</p>
	<p>
	Tämän ja muun lisäksi saat mahdollisuuden lähettää yksityisviestejä muille käyttäjille!
	</p>
</div>
{% endblock %}

web/templates/base.html
{% load utils %}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/ DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>.: Prkl :: {{ title }} :.</title>
	<link rel="index" title="Index" href="http://www.prkl.es/" />
	<link rel="shortcut icon" href="/media/pic/icon.png" />
	<link rel="stylesheet" href="/media/style.css" type="text/css" />
	<link rel="icon" type="image/png" href="/media/favicon.png" />
	<!-- script -->
	<script type="text/javascript" src="/media/jquery.js">
	</script>
	<script type="text/javascript">
	var setFormState = function(h, f, v) {
		$.ajax({
			type: "POST",
			url: "{% url set_form_visibility %}",
			data: "h=" + h  + "&f=" + f + "&v=" + v + "&csrfmiddlewaretoken=" + "{% do_csrf request %}",
		});
	}
	var toggleRegister = function() {
		if ($("#register_form").css("display") == "none") {
			$("#register_form").show(300, function() {
				setFormState("{{ request.true_id.hash }}", "regform", "true");
			});
			$("#toggle_reg").text("Piilota lomake");
		} else {
			$("#register_form").hide(300, function() {
				setFormState("{{ request.true_id.hash }}", "regform", "false");
			});
			$("#toggle_reg").text("Rekisteröidy");
		}
	}
	var togglePrklForm = function() {
		if ($("#prkl_form").css("display") == "none") {
			$("#prkl_form").show(300, function() {
				setFormState("{{ request.true_id.hash }}", "prklform", "true");
			});
			$("#toggle_prklform").text("Piilota lomake");
		} else {
			$("#prkl_form").hide(300, function() {
				setFormState("{{ request.true_id.hash }}", "prklform", "false");
			});
			$("#toggle_prklform").text("Kirjoita prkl");
		}
	}
	var voteClick = function(prkl_id, direction) {
		$.ajax({
			type: "POST",
			data: "prkl_id=" + prkl_id + "&direction=" + direction + "&csrfmiddlewaretoken=" + "{% do_csrf request %}&h=" + "{{ request.true_id.hash }}",
			url: "{% url vote %}",
			dataType: "json",
			success: function(retData) {
				if (retData['status'] == 'NOK') {
					if (retData['action'] == 'reload') {
						alert("Jos näet tämän, olet todennäköisesti kieltänyt cookiet");
						location.reload();
					}
				} else {
					// Update score
					scoreElem = $("#" + prkl_id + "_score");
					val = parseInt(scoreElem.text());
					val += parseInt(retData['message']);
					scoreElem.text(val);

					// Update menu
					elem = $("#" + prkl_id + "_plus");
					elem.fadeOut();

					elem = $("#" + prkl_id + "_minus");
					elem.fadeOut();

					scoreElem.animate({"margin-left": "0px"});
				}
			}
		});
	}
	var likeClick = function(prkl_id) {
		$.ajax({
			type: "POST",
			data: "prkl_id=" + prkl_id + "&csrfmiddlewaretoken=" + "{% do_csrf request %}&h=" + "{{ request.true_id.hash }}",
			url: "{% url like %}",
			dataType: "json",
			success: function(retData) {
				// Update menu
				elem = $("#" + prkl_id + "_like");
				if (retData["message"] == "yes") {
					elem.text("Älä tykkääkään");
				} else if (retData["message"] == "no") {
					elem.text("Tykkää");
				}
			}
		});
	}
	</script>
	{% block scripture %}
	{% endblock %}
	<!-- /script -->
</head>

<body>

<div class="top">
{% block menu %}
{% with request.META.PATH_INFO as req_path %}
{% url index as index_url %}
{% ifequal req_path "/" %}
<a href="{{ index_url }}" class="{% check_active req_path index_url %}">Pääsivu</a>
{% else %}
{% url index page results_per_page as index_stat_url %}
<a href="{{ index_url }}" class="{% check_active req_path index_stat_url %}">Pääsivu</a>
{% endifequal %}
{% if user.id %}
{% url member user.username as member_url %}
<a href="{{ member_url }}" class="{% check_active req_path member_url %}">Oma</a>
{% endif %}
{% url top as top_url %}
<a href="{{ top_url }}" class="{% check_active req_path top_url %}">Symppikset</a>
{% url bottom as bottom_url %}
<a href="{% url bottom %}" class="{% check_active req_path bottom_url %}">Hajottavat</a>
{% url random as random_url %}
<a href="{% url random %}" class="{% check_active req_path random_url %}">Satunnainen</a>
{% url faq as faq_url %}
<a href="{% url faq %}" class="{% check_active req_path faq_url %}">Tietoa</a>
{% url members as members_url %}
<a href="{% url members %}" class="{% check_active req_path members_url %}">Jäsenet</a>
{% url search as search_url %}
<a href="{% url search %}" class="{% check_active req_path search_url %}">Haku</a>
{% endwith %}
{% endblock %}
</div>

<div id="prkl-logo">
	<a href="{% url index %}">
		<img src="/media/prkl-logo.png" alt="prkl-logo"/>
	</a>
   <div id="avautuminen">
      <img src="/media/avautuminen_alkaa.png" alt="Avautuminen alkaa Tänään"/>
   </div>
</div>

<div class="left">
{% include "tags/login.html" %}
{% include "tags/register.html" %}
{% include "tags/recommend_vip.html" %}

{% block intro %}
{% endblock %}
</div>

<div class="right">
{% include "tags/member_search.html" %}
{% include "tags/invite_friend.html" %}
</div>

{% block prklform %}
<div class="prklbuffer">
</div>
{% endblock %}

<div class="content">
{% block content %}
{% endblock %}

<hr />
<small>
Sähköposti <a href="mailto:yllapito@prkl.es">yllapito@prkl.es</a>
</small>
</div>

{% if production %}
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
	var pageTracker = _gat._getTracker("UA-8888476-1");
	pageTracker._trackPageview();
} catch(err) {}
</script>
{% endif %}

</body>

web/templates/edit_profile.html
{% extends "base.html" %}

{% block scripture %}
{% if change_pic_form %}
{% include "tags/pic_js.html" %}
{% endif %}
{% endblock %}

{% block content %}
<h1>{{ member }}</h1>
<div class="member">
	<div id="member_data" class="member_data">
		{% include "tags/member_pic.html" %}

		<a class="do_edit_data" href="{% url member member.username %}">PROFIILIIN</a>

			<form method="POST" action="{{ request.META.PATH_INFO }}">
			{% if member.is_vip %}
			<div>
			{{ edit_description_form.as_prkl }}
			</div>
			{% endif %}
			<ul>
			{{ edit_profile_form.as_ul }}
			</ul>
			<input type="submit" name="submit" value="Muokkaa" />
			</form>

	</div>
</div>
{% endblock %}

web/templates/forgot_password.html
{% extends "base.html" %}

{% block scripture %}
<script type="text/javascript">
$(document).ready(function(){
	$("#id_email").focus();
});
</script>
{% endblock %}

{% block content %}
<div class="notfound">
<h1>
Tänään unohdin salasanani. prkl
</h1>
<p>
Annathan sähköpostiosoitteesi, niin lähetämme linkin, josta salasanan voi vaihtaa.
</p>
<form action="{% url forgot_password %}" method="POST">
<table>
	{{ request_reset_form.as_table }}
</table>
<input type="submit" name="submit" value="Pyydä linkki" />
</form>
{% if request_reset_form.is_bound and request_reset_form.is_valid %}
<p>Lähetetty!</p>
{% endif %}
</div>
{% endblock %}

web/templates/index.html
{% extends "base.html" %}

{% block scripture %}
<script type="text/javascript">
$(document).ready(function() {
	$("#id_content").focus();
});
</script>
{% endblock %}

{% block intro %}
{% ifequal strip_path "" %}
{% if not request.true_id.seen_intro %}
<div class="message">
	<h1>Tänään kerron tästä sivusta, prkl</h1>
	<p>
	Tälle sivustolle voit avautua, halutessasi anonyymisti, kunhan avautumisesi alkaa sanalla <b>Tänään</b>
	ja loppuu sanaan <b>prkl</b>.
	</p>
	<p>
	Myös tekstiviesti "<em>Tänään ...</em>" numeroon <em>16340</em>, vain <em>0.25e</em>!
	</p>
	<p>
	Tämä avautuminen on nimeltään <em>prkl</em>
	</p>
	<p>
	<small><a href="/?mark_intro=yes">Merkkaa tiedote luetuksi</a></small>
	</p>
</div>
{% endif %}
{% endifequal %}
{% endblock %}

{% block prklform %}
{% if submit_prkl_form %}
<div class="prklform">
	{% if request.true_id.visible_prklform %}
	<a id="toggle_prklform" href="#" onClick="togglePrklForm();">Piilota lomake</a>
	<div id="prkl_form" class="prkl_form" style="display: block;">
	{% else %}
	<a id="toggle_prklform" href="#" onClick="togglePrklForm();">Kirjoita prkl</a>
	<div id="prkl_form" class="prkl_form" style="display: none;">
	{% endif %}
		<form method="POST" action="{% url index %}">
		{{ submit_prkl_form.as_prkl }}

		<input type="submit" name="submit" value="Lisää" />
		<div>
		<small>
        <b>
		Voit myös lähettää tekstiviestin <em>Tänään ...</em> numeroon <em>16340</em>, vain <em>0.25e</em>.
		<br />
		Viesti on anonyymi.
        </b>
		</small>
		</div>
		</form>
	</div>
{% else %}
<div class="prklbuffer">
{% endif %}
</div>
{% endblock %}

{% block content %}
{% digg_paginator %}

<div class="prkls">

{% for prkl in page_objects.object_list %}
	{% include "tags/prkl_div.html" %}
{% endfor %}
</div>

{% digg_paginator %}
{% endblock %}

web/templates/member.html
{% extends "base.html" %}

{% block scripture %}
{% if change_pic_form %}
{% include "tags/pic_js.html" %}
{% endif %}
{% endblock %}

{% block content %}
<h1>{{ member }}</h1>
{% include "tags/member_menu.html" %}
<div class="member">
	<div id="member_data" class="member_data">
		{% include "tags/member_pic_edit.html" %}

		{% ifequal user.id member.user.id %}
		<a class="do_edit_data" href="{% url edit_profile %}">MUOKKAA TIETOJA</a>
		{% endifequal %}

        {% include "tags/member_data.html" %}
	</div>

	<div class="member_likes">
		{% if member_likes %}
		<h2>Näistä prkleistä {{ member.username }} tykkää</h2>
		<div class="prkls">
			{% for prkl in member_likes %}
			{% include "tags/prkl_div.html" %}
			{% endfor %}
		</div>
		{% else %}
			{{ member.username }} ei ole vielä tykännyt yhdestäkään prkleestä o_O
		{% endif %}
	</div>

	{% if member.is_vip %}
	{% ifequal member user %}
	<div id="vip_data" class="vip_data">
	<h2>Näistä prkleistäsi tykätään</h2>
	{% if liked_prkls %}
		<div class="prkls">
		{% for prkl in liked_prkls %}
			{% include "tags/prkl_div.html" %}
		{% endfor %}
		</div>
	{% else %}
		Sinun prkleistä ei ole vielä pidetty
	{% endif %}
	</div>
	{% endifequal %}
	{% endif %}
</div>
{% endblock %}

web/templates/members.html
{% extends "base.html" %}

{% block scripture %}
{% if user.id and user.is_vip %}
<script type="text/javascript">
$(document).ready(function() {
	$("#id_find_friend").focus();
});
</script>
{% endif %}
{% endblock %}

{% block content %}
{% digg_paginator %}
<div class="members">
	{% for member in page_objects.object_list %}
    {% include "tags/member_div.html" %}
	{% endfor %}
</div>
{% endblock %}

web/templates/only_registered.html
{% extends "base.html" %}


{% block scripture %}
<script type="text/javascript">
$(document).ready(function() {
	$("#id_reg_username").focus();
});
</script>
{% endblock %}

{% block content %}
<h1>Rekisteröityminen kannattaa!</h1>

<div>
Hakemasi sivu on saatavilla rekisteröityneille käyttäjille. Kannattaa siis liittyä heti seuraan!
</div>

{% endblock %}

web/templates/only_vip.html
{% extends "base.html" %}


{% block scripture %}
<script type="text/javascript">
$(document).ready(function() {
	$("#id_reg_username").focus();
});
</script>
{% endblock %}

{% block content %}
<h1>Liity VIPiksi jo tänään prkl!</h1>

<div>
Hakemasi sivu on vain VIP-käyttäjille, joten kannattaa tilata VIP-aikaa heti!
</div>

{% endblock %}

web/templates/prkl.html
{% extends "base.html" %}

{% block scripture %}
<script type="text/javascript">
$(document).ready(function() {
	$("#id_content").focus();
	var logo = $('#prkl-logo');
	var offset = logo.offset().top;
	$('html, body').animate({
		scrollTop: offset
	}, 1000)
});
</script>
{% endblock %}

{% block content %}
<div class="prkls">
	{% include "tags/prkl_div.html" %}
</div>

<div class="comments">
	{% for comment in comments %}
	<div class="comment">
		<span class="comment_content">
		{{ comment.content }}
		</span>
		<br />
		<span class="comment_user">
		{% if comment.commenting_user_id %}
		<a href="{% url member comment.commenting_user %}">{{ comment.commenting_user }}</a>
		{% else %}
		Anonyymi
		{% endif %}
		</span>
		<span class="comment_date">
		{{ comment.tstamp|date:"Y-m-d H:i:s" }}
		</span>
	</div>
	{% endfor %}
	<div class="commentform">
	<form method="POST" action="{{ request.META.PATH_INFO }}">
	{{ comment_prkl_form.as_prkl }}
	<br />
	<input type="submit" name="submit" value="Kommentoi" />
	</form>
	</div>
</div>

{% endblock %}

web/templates/reset_password.html
{% extends "base.html" %}

{% block scripture %}
<script type="text/javascript">
$(document).ready(function(){
	$("#id_new_password").focus();
});
</script>
{% endblock %}


{% block content %}
<div class="notfound">
<h1>
Tänään vaihdan salasanani. prkl
</h1>
<p>
Annettuasi uuden salasanasi, sinut kirjataan suoraan sisään!
</p>
<form action="{% url reset_password token %}" method="POST">
<table>
	{{ password_reset_form.as_table }}
</table>
<input type="submit" name="submit" value="Vaihda" />
</form>
</div>
{% endblock %}

web/templates/search.html
{% extends "base.html" %}

{% block scripture %}
<!--
<script type="text/javascript">
$(document).ready(function() {
	$("#id_content").focus();
});
</script>
-->
{% endblock %}

{% block content %}
<h1>Tänään haen kunnolla prkl</h1>
<div class="search">
	<form method="GET" action="{{ request.META.PATH_INFO }}">
	{% include "tags/search_form_content.html" %}
	<input type="submit" name="submit" value="Etsi" />
	</form>
</div>

{% if page_objects.object_list %}
{% digg_paginator %}
<div class="members">
{% for member in page_objects.object_list %}
{% include "tags/member_div.html" %}
{% endfor %}
</div>
{% endif %}

{% endblock %}